name: Update GitHub Trophies

on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight UTC
  workflow_dispatch: # Allows you to trigger it manually anytime

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophy Card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=md-zeon&theme=darkhub'
          path: github-profile-trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Trophy Card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-profile-trophy.svg
          git commit -m "chore: update github profile trophies" || exit 0
          git push
